# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b3b6e64227e1be800267e9150c259ec2f2cc246291d3a84a00ce3142c325cd6566894129051858f2de2c3b93ccddcfc80235410ac6597f1d82abdfe6c65837ad

test:
  secret_key_base: f709945e2a8f537369f7c3afc2cfa2dcb918a899e06e80c0638afbbf6681953e78f4f0639d843a1d2fc9463155501fe068e7abbb59ea7ea62a799c5d594dd01d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
